SET IDENTITY_INSERT [dbo].[Product] ON

INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (17, N'Vans Ouroboros Slip-On', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
 N'cam kết chính hãng'', 5, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/vans7.png', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (18, N'Vans Ouroboros SK8-HI', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
 N'cam kết chính hãng'', 5, CAST(2100000.00 AS Decimal(18, 2)), N'~/Content/images/vans8.png', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (19, N'Vans x National Geographic SK8-HI Reissue 138', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
 N'cam kết chính hãng'', 5, CAST(3100000.00 AS Decimal(18, 2)), N'~/Content/images/vans9.png', -56)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (20, N'Vans X Moca Judy Baca Authentic', N'Vans là thương hiệu thời trang chuyên về giày trượt ván, quần áo và phụ kiện của Mỹ, được thành lập tại Anaheim, California và thuộc sở hữu của tập đoàn VF Corporation.Giày Vans siêu nổi tiếng thực chất là một thương hiệu ván trượt với giá trị hàng tỷ đô đến từ nước Mỹ. Ngay từ phong cách, thiết kế, chúng ta cũng thấy bật lên những đường nét quen thuộc của những anh chàng người Mỹ trẻ tuổi, năng động, khỏe khoắn và siêu ngầu.Những đôi giày mà Vans mang lại đều có thể phổ cập đến nhiều tín đồ mê giày trên toàn thế giới. Giá thành rẻ , đa dạng kiểu dáng và màu sắc.
 N'cam kết chính hãng'', 5, CAST(2850000.00 AS Decimal(18, 2)), N'~/Content/images/vans10.png', 98)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (21, N'Converse Chuck Taylor All Star 70 Plus', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(2500000.00 AS Decimal(18, 2)), N'~/Content/images/Converse1.jpg', 99)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (22, N'Converse Chuck Taylor All Star Dainty', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(1500000.00 AS Decimal(18, 2)), N'~/Content/images/Converse2.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (23, N'Converse Chuck Taylor All Star Lift Platform Canvas', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(1800000.00 AS Decimal(18, 2)), N'~/Content/images/Converse3.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (24, N'Converse Chuck Taylor All Star 1970s Archive Paint Splatter', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(2500000.00 AS Decimal(18, 2)), N'~/Content/images/Converse4.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (25, N'Converse Chuck Taylor All Star 1970s My Story', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(2000000.00 AS Decimal(18, 2)), N'~/Content/images/Converse5.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (26, N'Converse Chuck Taylor All Star Double Stack Lift My Story', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(1800000.00 AS Decimal(18, 2)), N'~/Content/images/Converse6.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (27, N'Converse Chuck Taylor All Star Wordmark', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/Converse7.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (28, N'Converse Chuck Taylor All Star Gamer Low-Top', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(1000000.00 AS Decimal(18, 2)), N'~/Content/images/Converse8.jpg', 99)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (29, N'Converse Chuck Taylor All Star Valentine''s Day', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/Converse9.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (30, N'Converse Chuck Taylor All Star 1970s Mi Gente', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(2000000.00 AS Decimal(18, 2)), N'~/Content/images/Converse10.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (31, N'Converse Chuck Taylor All Star Create Future', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/Converse12.jpg', 100)
INSERT INTO [dbo].[Product] ([ProductID], [NamePro], [DecriptionPro], [CateID], [Price], [ImagePro], [Quantity]) VALUES (32, N'Converse Chuck Taylor All Star Twisted Classic Logo Play', N'Converse có lịch sử phát triển lâu đời hơn các dòng giày thể thao như Nike và Adidas. Năm 1908, Hầu tước M. Converse thành lập Công ty Giày cao su Converse ở Malden, Massachusetts. Đây chỉ là bước khởi đầu của thương hiệu, năm 1915 Converse bắt đầu sản xuất giày tennis, đây là bước ngoặt quan trọng trong lịch sử của Converse khi giày bóng rổ Converse All-Star được đưa ra thị trường vào năm 1917. Converse All Star đã trở thành đôi giày được chỉ định cho trận đấu bóng rổ quốc tế của Mỹ.Ưu điểm của Converse Classic là: rẻ, bền, đẹp. Một đôi giày phù hợp với tất cả mọi người, phù hợp với mọi set đồ của bạn. Đặc biệt sau hàng trăm năm lịch sử, công trình này chưa bao giờ lỗi thời.
 N'cam kết chính hãng'', 2, CAST(1600000.00 AS Decimal(18, 2)), N'~/Content/images/Converse11.jpg', 100)
SET IDENTITY_INSERT [dbo].[Product] OFF
